import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Oswald } from 'next/font/google';
import Navbar from "./Components/Navbar";

const oswald = Oswald({ subsets: ['latin'], weight: ['400', '500', '700'] });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Techno-Quest-3.O",
  description: "Generated by Simon Leo Alexander",
};

export default function RootLayout({ children }) {
  return (
    <>
    <html lang="en">
      <body
        className={oswald.className}
      >
        {children}
      </body>
    </html>
    </>
  );
}
