import "./globals.css";
import Navbar from "./Components/Navbar";

export const metadata = {
  title: "Techno-Quest-3.O",
  description: "Generated by Simon Leo Alexander",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
      </body>
    </html>
  );
}

// import localFont from "next/font/local";
// import { Oswald } from "next/font/google";
// import "./globals.css";
// import Navbar from "./Components/Navbar";

// // Google font
// const oswald = Oswald({ subsets: ["latin"], weight: ["400", "500", "700"] });

// // Local fonts
// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff2", // place the font file in /app/fonts or /public/fonts
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });

// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff2",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

// export const metadata = {
//   title: "Techno-Quest-3.O",
//   description: "Generated by Simon Leo Alexander",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`${oswald.className} ${geistSans.variable} ${geistMono.variable}`}>
//         <Navbar />
//         {children}
//       </body>
//     </html>
//   );
// }
